name: stock-platform
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  # Database
  - psycopg2
  - sqlalchemy
  # Data handling
  - pandas
  - numpy
  # HTTP Client
  - requests
  - python-dotenv
  # Visualization libraries
  - panel
  - plotly
  - bokeh
  - hvplot
  - param
  - holoviews
  # Spyder kernel f√ºr das Environment
  - spyder-kernels
  # Jupyter (optional, falls du Notebooks nutzen willst)
  - ipykernel

  # Pip-only packages
  - pip:
    - timescaledb
    - pandas-ta
